{
  "version": 2,
  "builds": [
    {
      "src": "server.js",
      "use": "@vercel/node"
    },
    {
      "src": "index.html",
      "use": "@vercel/static"
    }
  ],
  "routes": [
    {
      "src": "/api/(.*)",
      "dest": "/server.js"
    },
    {
      "src": "/(.*)",
      "dest": "/$1"
    }
  ],
  "env": {
    "PLAID_CLIENT_ID": "@plaid_client_id",
    "PLAID_SECRET": "@plaid_secret",
    "PLAID_ENV": "sandbox"
  }
}
